# Generated by Django 2.1.4 on 2019-01-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
