# Generated by Django 2.1.4 on 2018-12-31 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapi',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3134d5a-5bba-42a2-b23c-b51fbe385338'), editable=False, primary_key=True, serialize=False),
        ),
    ]
