# Generated by Django 2.1.4 on 2018-12-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181231_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapi',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
