# Generated by Django 2.1.4 on 2019-01-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20181231_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('typedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TypeData')),
            ],
        ),
        migrations.RemoveField(
            model_name='userapi',
            name='json',
        ),
        migrations.AddField(
            model_name='userapidata',
            name='userapi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.UserApi'),
        ),
    ]
