# Generated by Django 2.1.4 on 2019-01-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190101_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeData',
        ),
    ]
