# Generated by Django 2.1.4 on 2019-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20190101_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapidata',
            name='userapi',
        ),
        migrations.AddField(
            model_name='userapi',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.DeleteModel(
            name='UserApiData',
        ),
    ]
