# Generated by Django 2.1.4 on 2018-12-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181228_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.png', upload_to='news_pics'),
        ),
    ]
