# Generated by Django 2.1.4 on 2018-12-29 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181229_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='new_to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
